export interface RealWorldUse {
  item: string;
  use: string;
}

export const REAL_WORLD_USES: Record<number, RealWorldUse> = {
  1: { item: "Bahan Bakar Roket & Air", use: "Digunakan sebagai bahan bakar pesawat luar angkasa dalam wujud cair dan merupakan unsur pembentuk air (H₂O)." },
  2: { item: "Balon Helium & Pendingin MRI", use: "Gas pengisi balon udara karena sangat ringan dan aman, serta pendingin magnet superkonduktor pada pemindai MRI." },
  3: { item: "Baterai Gadget (Lithium-Ion)", use: "Menyimpan energi densitas tinggi pada smartphone, laptop, powerbank, dan kendaraan listrik masa depan." },
  4: { item: "Kaca Tabung Sinar-X & Dirgantara", use: "Digunakan sebagai paduan logam kedirgantaraan karena sangat tangguh namun berbobot sangat ringan." },
  5: { item: "Peralatan Masak Pyrex & Serat Gelas", use: "Bahan pembuat kaca borosilikat yang tahan perubahan suhu ekstrem dan serat kaca bodi otomotif." },
  6: { item: "Pensil Grafit & Cincin Intan", use: "Membentuk grafit lunak untuk menulis serta intan super-keras untuk perhiasan dan mata gergaji industri." },
  7: { item: "Pupuk Urea & Pendingin Cryogenic", use: "Menyuburkan tanaman via pupuk nitrogen serta mengawetkan sampel biologis medis dalam bentuk cair." },
  8: { item: "Tabung Oksigen Medis & Penyelaman", use: "Sangat krusial untuk terapi pernapasan darurat di rumah sakit dan penyelam laut dalam." },
  9: { item: "Pasta Gigi (Fluoride) & Lapisan Teflon", use: "Mencegah gigi berlubang melalui fluoridasi serta bahan dasar pelapis antilengket panci premium." },
  10: { item: "Lampu Neon Hias & Lampu Kilat", use: "Memancarkan cahaya merah-oranye menyala ikonik pada lampu reklame kota dan dekorasi estetik." },
  11: { item: "Garam Dapur & Lampu Jalan Kuning", use: "Memberi rasa asin alami pengawet makanan serta pengisi lampu jalanan tua berdaya tembus kabut tinggi." },
  12: { item: "Velg Mobil Balap & Obat Maag", use: "Bahan logam paduan super ringan untuk velg balap serta bahan aktif antasida penetral asam lambung." },
  13: { item: "Kaleng Minuman & Bodi Pesawat Terbang", use: "Bodi pesawat terbang modern, aluminium foil pembungkus makanan, dan kusen jendela rumah." },
  14: { item: "Chip Komputer & Panel Surya", use: "Bahan dasar utama mikroprosesor komputer, memori telepon pintar, dan sel fotovoltaik surya." },
  15: { item: "Kepala Korek Api & Pupuk NPK", use: "Zat aktif pemantik api pada korek kayu serta penyusun nutrisi akar fosfor untuk dunia pertanian." },
  16: { item: "Aki Kendaraan & Ban Karet", use: "Bahan utama asam sulfat pengisi baterai mobil serta agen vulkanisasi penguat karet ban kendaraan." },
  17: { item: "Kaporit Kolam Renang & Pipa PVC", use: "Disinfektan pembasmi kuman air kolam serta penyusun monomer pipa saluran air paralon plastik." },
  18: { item: "Pengelasan Logam & Lampu Pijar", use: "Gas pelindung las busur suhu tinggi agar logam tidak teroksidasi dan pengisi bohlam lampu." },
  19: { item: "Pupuk Kalium & Keseimbangan Elektrolit", use: "Pupuk penyubur buah tanaman serta ion elektrolit pengatur detak jantung dan saraf otot tubuh." },
  20: { item: "Susu Kekuatan Tulang & Semen Cor", use: "Menyusun struktur kalsium tulang/gigi mamalia dan bahan pengikat batuan pada beton konstruksi." },
  21: { item: "Lampu Stadion & Rangka Sepeda Premium", use: "Paduan logam scandium-aluminium memberikan kekuatan ekstra pada rangka sepeda balap dan lampu sorot." },
  22: { item: "Implan Medis Tulang & Turbin Jet", use: "Logam biokompatibel untuk implan gigi maupun pen tulang patah serta bodi pesawat jet tempur supersonic." },
  23: { item: "Kunci Pas Baja Antigores & Pegas", use: "Ditambahkan pada paduan baja vanadium membuat peralatan mekanik menjadi luar biasa keras dan lentur." },
  24: { item: "Lapisan Stainless Steel Chrome & Bemper", use: "Memberikan efek kilau berkaca-kaca serta perlindungan mutlak terhadap oksidasi karat logam besi." },
  25: { item: "Baterai Alkali & Struktur Rel Kereta", use: "Digunakan sebagai elektroda pada baterai kering dan meningkatkan ketangguhan baja rel kereta api." },
  26: { item: "Konstruksi Jembatan & Kerangka Gedung", use: "Logam paling penting dalam peradaban manusia untuk beton bertulang, kendaraan, dan industri manufaktur." },
  27: { item: "Baterai Mobil Listrik & Magnet Alnico", use: "Komponen katoda esensial pada baterai lithium mobil listrik guna ketahanan penyimpanan daya yang lama." },
  28: { item: "Uang Koin Logam & Senar Gitar Listrik", use: "Bahan pembuatan koin logam pecahan, turbin gas, serta senar gitar magnetic bermutu tinggi." },
  29: { item: "Kabel Listrik & Kumparan Dinamo", use: "Penghantar listrik terbaik setelah perak, digunakan pada kabel rumah tangga dan trafo generator." },
  30: { item: "Galvanisasi Pelindung Karat & Suplemen", use: "Pelapis anti karat tiang listrik baja serta mikronutrisi pelindung imunitas tubuh manusia." },
  31: { item: "Termometer Suhu Tinggi & LED Biru", use: "Logam unik mencair di tangan, digunakan pada laser semikonduktor biru dan termometer medis suhu tinggi." },
  32: { item: "Kanal Serat Optik & Lensa Inframerah", use: "Digunakan pada lensa teropong malam inframerah militer dan kaca pengarah kabel data internet." },
  33: { item: "Pestisida Pertanian & Semikonduktor GaAs", use: "Terkenal sebagai racun kuat, namun juga digunakan dalam paduan silikon sirkuit terpadu berkecepatan tinggi." },
  34: { item: "Mesin Fotokopi & Sel Fotolistik", use: "Bahan konduksi peka cahaya pada alat fotokopi serta pemberi warna merah cantik pada kaca artistik." },
  35: { item: "Bahan Pemadam Api & Obat Penenang", use: "Cairan halogen merah pembuat zat penghambat api kabel elektronik serta sintesis bahan farmasi." },
  36: { item: "Lampu Flash Kamera & Laser Pengukur Jarak", use: "Memancarkan cahaya putih cemerlang pada lampu sorot landasan pacu bandara dan lampu kilat fotografi." },
  37: { item: "Jam Atom Global & Riset Laser", use: "Digunakan dalam riset osilator laser super dingin dan sistem navigasi satelit global presisi tinggi." },
  38: { item: "Kembang Api Merah & Sensor Oksigen", use: "Memberikan kilatan merah tua spektakuler pada pertunjukan kembang api perayaan malam." },
  39: { item: "Kaca Lensa Mikroskop & Tabung Televisi", use: "Digunakan untuk meningkatkan kejernihan lensa kamera berkualitas tinggi dan fosfor gambar TV tabung." },
  40: { item: "Permata Kubik Zirconia & Reaktor Nuklir", use: "Bahan permata sintetis pengganti berlian dan dinding anti-korosi tangki pembelahan nuklir." },
  41: { item: "Magnet Mesin MRI & Pesawat Ruang Angkasa", use: "Paduan superkonduktor magnetik kuat untuk mesin pemindai rumah sakit dan rangka satelit." },
  42: { item: "Baja Alat Bor Kecepatan Tinggi & Militer", use: "Logam bertitik lebur sangat tinggi, mencegah baja melunak akibat gesekan panas mesin bubut." },
  43: { item: "Pelacak Medis Tumor & Kanker", use: "Isotop radioaktif artifisial teringan yang disuntikkan ke tubuh untuk memetakan lokasi kanker." },
  44: { item: "Kontak Saklar Listrik Daya Tinggi", use: "Logam tahan aus ekstrem untuk ujung kontak relay listrik dan tip pulpen eksekutif." },
  45: { item: "Pelapis Cincin Emas Putih & Cermin Laser", use: "Logam termahal yang disepuh ke atas perhiasan perak/emas putih agar berkilau perak mewah dan tahan gores." },
  46: { item: "Filter Emisi Knalpot Mobil (Catalytic)", use: "Berfungsi menyerap emisi gas beracun karbon monoksida dari mesin kendaraan menjadi udara aman." },
  47: { item: "Perhiasan Perak, Sendok, & Solder Medis", use: "Reflektor cahaya alami terunggul untuk cermin berkualitas tinggi, kontak panel surya, dan perhiasan." },
  48: { item: "Baterai Isi Ulang Ni-Cad & Pigmen Kuning", use: "Zat kuning cerah pada cat minyak pelukis legendaris serta plat baterai isi ulang zaman dulu." },
  49: { item: "Layar Sentuh Handphone (ITO)", use: "Melalui campuran Indium Tin Oxide, menghasilkan lapisan transparan elektrik penghantar sentuhan jari kita." },
  50: { item: "Solder Elektronika & Kaleng Makanan", use: "Dipadukan dengan timbal untuk menyolder komponen sirkuit PCB komputer dan melapisi kaleng susu." },
  51: { item: "Plat Baterai Kendaraan & Bahan Tahan Api", use: "Memperkeras logam timbal pada sel baterai basah mobil dan bahan pelapis pakaian tahan api." },
  52: { item: "Lapisan Panel Surya & Keramik", use: "Bahan aditif semikonduktor meningkatkan efisiensi pengubahan panas surya menjadi listrik." },
  53: { item: "Obat Luka Betadine & Hormon Tiroid", use: "Zat antiseptik merah pembunuh bakteri pada goresan luka serta zat esensial kelenjar tiroid leher." },
  54: { item: "Lampu Kilat Xenon Mobil & Lampu Proyektor", use: "Pengisi tabung lampu depan kendaraan mewah dengan cahaya putih biru menyala menembus malam." },
  55: { item: "Jam Atom GPS Presisi Sangat Tinggi", use: "Menghasilkan getaran frekuensi super-akurat pengatur detak waktu satelit penentu peta GPS." },
  56: { item: "Pencitraan Sinar-X Lambung (Barium Meal)", use: "Cairan suspensi barium diminumkan ke pasien agar kontras jalur lambung terlihat jelas di foto rontgen." },
  57: { item: "Kaca Kamera Premium & Teleskop", use: "Bahan kaca indeks bias tinggi mereduksi aberasi warna pada lensa kamera DSLR profesional." },
  58: { item: "Batu Pemantik Korek Api & Filter Knalpot", use: "Paduan logam piroforik melontarkan percikan bunga api panas saat digesek roda gerigi pemantik." },
  59: { item: "Kacamata Las Pelindung Mata & Filter Kuning", use: "Menyerap cahaya radiasi ultraviolet berbahaya yang terpancar dari proses pengelasan industri baja." },
  60: { item: "Magnet NdFeB Super Kuat & Hard Disk", use: "Membuat speaker mini handphone, motor penggerak mobil listrik, dan kumparan pembaca cakram harddisk." },
  61: { item: "Baterai Nuklir Mini & Detektor Ketebalan", use: "Memanfaatkan energi peluruhan partikel beta menghasilkan pasokan daya listrik tahan puluhan tahun." },
  62: { item: "Magnet Kobalt Berdaya Tahan Panas Tinggi", use: "Magnet motor penggerak mesin jet militer yang bekerja pada suhu operasional di atas 300°C." },
  63: { item: "Fosfor Merah Layar TV & Detektor Uang Palsu", use: "Zat pendar fluorescent merah pada uang kertas yang menyala jika disinari senter ultraviolet polisi." },
  64: { item: "Zat Kontras MRI Medis & Magnet Super", use: "Logam bumi langka paramagnetik disuntikkan ke pembuluh darah menonjolkan bagian sel abnormal." },
  65: { item: "Layar Hijau Fosfor & Sensor Laser", use: "Menghasilkan warna hijau cerah pada komponen layar pemindai radar kapal dan lampu dekoratif." },
  66: { item: "Aditif Magnet Neodymium Tahan Panas", use: "Menjaga magnet mobil listrik agar tidak kehilangan daya tariknya ketika bekerja pada putaran mesin tinggi." },
  67: { item: "Mata Bor Laser Bedah & Pencitraan", use: "Digunakan sebagai dopan laser padat memotong jaringan biologis tubuh secara presisi tanpa berdarah." },
  68: { item: "Penguat Sinyal Kabel Serat Optik Bawah Laut", use: "Menstimulasi dan memperkuat pancaran pulsa cahaya data internet yang melemah di dasar samudra." },
  69: { item: "Sinar-X Gigi Portabel & Laser Gigi", use: "Menghasilkan radiasi sinar rontgen portable berenergi rendah tanpa membutuhkan pasokan listrik raksasa." },
  70: { item: "Sensor Gempa Lembah Patahan Bumi", use: "Digunakan pada sensor tegangan mekanik berskala mikro guna mencatat pergeseran patahan lempeng bumi." },
  71: { item: "Pemindai Medis Kanker Otak (PET Scan)", use: "Dopan kristal sensitif pada alat detektor kedokteran untuk memetakan penyebaran sebaran sel tumor." },
  72: { item: "Batang Kendali Reaktor Kapal Selam Nuklir", use: "Logam penyerap neutron yang luar biasa tangguh menolak korosi air laut bersuhu tinggi reaktor." },
  73: { item: "Pin Tulang Medis & Kapasitor HP", use: "Logam inert yang tidak bereaksi dengan jaringan biologis tubuh manusia, sempurna untuk penyangga tulang patah." },
  74: { item: "Filamen Lampu Pijar Klasik & Amunisi Baja", use: "Logam titik lebur terpanas (3422°C) penyusun kawat lampu pijar dan jangkar pengeboran bumi." },
  75: { item: "Nozel Mesin Jet Super & Katalis Turbin", use: "Logam tahan korosi suhu ekstrem ditambahkan ke baling-baling kompresor jet komersial." },
  76: { item: "Ujung Pena Mewah & Jarum Fonograf Klasik", use: "Logam berkepadatan tertinggi di dunia, sangat awet dari kikisan gesekan kertas maupun piringan hitam." },
  77: { item: "Busi Racing Balap & Standar Kilogram Lama", use: "Bahan elektroda busi bersuhu tinggi serta bahan baku pembuatan replika balok standar massa dunia." },
  78: { item: "Konverter Gas Buang, Kemoterapi, & Cincin", use: "Katalis industri penyaring asap mobil serya bahan obat anti-kanker cisplatin penahan pembelahan sel." },
  79: { item: "Konektor Kabel Audio Berlapis Emas & Cincin", use: "Logam mulia paling stabil yang tidak bisa berkarat sama sekali, mengamankan transmisi sirkuit mikro." },
  80: { item: "Termometer Suhu Tubuh & Lampu Hemat Energi", use: "Satu-satunya logam berbentuk cair pada suhu kamar, digunakan untuk sensor suhu merkuri tradisional." },
  81: { item: "Sensor Deteksi Radiasi Inframerah", use: "Sangat sensitif terhadap perubahan panjang gelombang cahaya inframerah untuk detektor optik." },
  82: { item: "Tameng Pelindung Radiasi Rontgen", use: "Lempengan logam sangat padat dipasang pada ruang radiologi guna memblokir pancaran bahaya sinar-X." },
  83: { item: "Obat Cair Sakit Perut (Pepto-Bismol)", use: "Senyawa bismut subsalisilat meredakan gangguan dinding pencernaan asam lambung dan diare ringan." },
  84: { item: "Pembangkit Arus Listrik Satelit Luar Angkasa", use: "Mengkonversi energi panas rontgen partikel menjadi listrik stabil bagi satelit penjelajah angkasa." },
  85: { item: "Radioterapi Kanker Kelenjar Tiroid", use: "Unsur sangat langka yang menembakkan energi alfa dalam jarak mikro menghancurkan target sel kanker." },
  86: { item: "Detektor Konsentrasi Gas Tanah & Terapi", use: "Gas mulia radioaktif berat, digunakan memantau keretakan geologi bawah tanah indikator gempa." },
  87: { item: "Penelitian Fisika Spektroskopi Nuklir", use: "Unsur alkali radioaktif terlangka di lapisan bumi, hanya diproduksi di laboratoriun untuk riset atom." },
  88: { item: "Jarum Luminous Arloji Vintage & Terapi Kanker", use: "Pernah digunakan membuat angka jam menyala hijau mandiri pada malam hari sebelum dilarang karena radiasi." },
  89: { item: "Terapi Radiasi Sel Kanker Stadium Lanjut", use: "Menghasilkan partikel berenergi luar biasa mumpuni membongkar rantai DNA tumor ganas." },
  90: { item: "Lampu Penerangan Camping Gas & Reaktor Aman", use: "Kaos lampu gantung petromaks agar bercahaya putih menyala hangat dan bahan reaktor alternatif." },
  91: { item: "Riset Geokimia Lapisan Batuan Purba", use: "Isotop penanda laju peluruhan sedimen guna menghitung umur lapisan fosil bumi jutaan tahun lalu." },
  92: { item: "Bahan Bakar Pembangkit Listrik Nuklir (PLTN)", use: "Unsur berat dipecah dalam reaksi fisi terkendali membangkitkan uap air penggerak generator listrik kota." },
  93: { item: "Sensor Detektor Detak Neutron Cepat", use: "Digunakan di dalam instrumen sains guna memantau aktivitas aliran radiasi neutron di ruang kendali nuklir." },
  94: { item: "Generator Baterai Voyager Angkasa (RTG)", use: "Menjadi sumber energi listrik awet tanpa sinar surya bagi wahana Voyager menembus batas tata surya." },
  95: { item: "Alat Detektor Asap Langit-Langit Rumah", use: "Isotop Americium memancarkan arus ionisasi udara yang akan terganggu jika ada partikel asap kebakaran." },
  96: { item: "Alat Pemecah Komposisi Batuan Planet Mars", use: "Dipasang pada lengan robotik rover pemantau Mars guna menembakkan sinar alfa membaca jenis mineral." },
  97: { item: "Sintesis Unsur Berat Baru Laboratorium", use: "Menjadi target pemboman partikel berenergi guna mereaksikan unsur-unsur trans-uranium baru." },
  98: { item: "Detektor Air Tanah & Pemicu Reaktor", use: "Menembakkan jutaan neutron per detik guna memecahkan kadar minyak bumi dan memandu aktivasi reaktor." },
  99: { item: "Kalibrator Spektrometer Debu Bom Termonuklir", use: "Pertama kali terdeteksi dari puing ledakan bom termonuklir, digunakan murni sebagai kalibrator sains." },
  100: { item: "Riset Fisika Mekanika Molekuler Nuklir", use: "Diproduksi melalui reaktor neutron fluks tinggi guna memicu formasi isotop berat buatan." },
  101: { item: "Studi Reaksi Fusi Intan Peluruhan Massa", use: "Unsur sintetis pertama yang dipisahkan secara kimiawi untuk membuktikan keteraturan tabel periodik Mendeleev." },
  102: { item: "Riset Kimia Komparatif Unsur Superberat", use: "Dibuat lewat akselerator linear untuk mempelajari tingkat kestabilan ikatan elektron kulit terluar." },
  103: { item: "Eksperimen Interaksi Logam Trans-Aktinida", use: "Penutup deret Aktinida yang digunakan untuk membuktikan efek relativistik pada struktur atom berat." },
  104: { item: "Fisika Teoretis & Struktur Nuklir Artifisial", use: "Unsur buatan supercepat meluruh, digunakan murni untuk riset laboratorium batas maksimal inti atom." },
  105: { item: "Riset Waktu Paruh & Peluruhan Partikel Berat", use: "Membantu menyingkap model cangkang nuklir dalam menyerap dan melepaskan energi radiasi." },
  106: { item: "Eksperimen Akselerator Partikel Sintetis", use: "Dibuat dengan menggabungkan ion kalium dengan kalifornium guna mendalami konsep kestabilan transisi." },
  107: { item: "Verifikasi Teori Mekanika Kuantum Relativistik", use: "Membantu fisikawan mengonfirmasi bagaimana elektron baris ketujuh berotasi mendekati kecepatan cahaya." },
  108: { item: "Studi Gasifikasi Organometalik Unsur Berat", use: "Digunakan untuk membentuk senyawa kimia fasa gas guna menguji kesamaan golongan logam transisi." },
  109: { item: "Pengujian Gaya Tolak Elektrostatik Inti Atom", use: "Mempelajari perilaku fisika inti atom yang sangat tidak stabil akibat kepadatatan proton tinggi." },
  110: { item: "Studi Batas Maksimum Muatan Positif", use: "Pemboman atom timbal dengan nikel menghasilkan unsur superberat guna batas fisika kuantum klasik." },
  111: { item: "Penelitian Efek Kontraksi Kulit Elektron Terluar", use: "Mempelajari pengaruh relativitas khusus pada orbital d dan s pada keluarga logam coinage." },
  112: { item: "Pengukuran Densitas & Sifat Fisis Trans-Aktinida", use: "Digunakan murni untuk mengamati apakah unsur baris ke-7 ini berwujud cair atau gas pada suhu ruang." },
  113: { item: "Riset Sintesis Nuklir Asia Pasifik", use: "Membuktikan kontribusi institusi riset regional Asia dalam menciptakan atom baru di tabel periodik." },
  114: { item: "Studi 'Pulau Kestabilan' Fisika Inti (Island of Stability)", use: "Diteliti intensif guna membuktikan teori adanya area nomor atom tinggi yang memiliki waktu paruh stabil panjang." },
  115: { item: "Riset Peluruhan Alfa Terpandu Berenergi Tinggi", use: "Diproduksi dalam jumlah atom tunggal untuk menganalisis pembagian energi kinetik partikel alfa." },
  116: { item: "Validasi Model Cangkang Energi Kuantum", use: "Melacak skema transisi energetik dari atom darmstadtium menuju peluruhan timbal akhir." },
  117: { item: "Sintesis Unsur Halogen Terberat di Bumi", use: "Menjadi mata rantai terbaru pembuktian keteraturan kenaikan reaktivitas golongan halogen." },
  118: { item: "Eksperimen Batas Akhir Baris Tabel Periodik", use: "Unsur bermuatan proton terbesar yang berhasil diproduksi peradaban manusia saat ini." }
};
